### ISSUE TITLE
SSTG-0.1.0.4 build fails during haddock stage

### ISSUE THREAD

**Issue by peti** [AntonXue/SSTG#1]
Citing from https://nix-cache.s3.amazonaws.com/log/db3ss486v76x0l1hrgi3a9hmyqrg5r8r-SSTG-0.1.0.4.drv:

~~~
src/SSTG/Core/Execution/Rules.hs:256:3: error:
    parse error on input ‘-- | Rule Con App’
~~~

**Comment by AntonXue** [comment]
Thanks for bringing this up! It turns out haddock generation is fairly simple with `stack haddock`. I've fixed this error in version `0.1.0.5`, and uploaded it to hackage: https://hackage.haskell.org/package/SSTG

SSTG is still very much in its infancy and is missing SMT that make it fully useful as a symbolic execution engine, but thank you for the interest nonetheless!
